export const ACTIONS = {
  UPDATE_ATTRIBUTE: 'UPDATE_ATTRIBUTE',
  UPDATE_CURRENT_VIEW: 'UPDATE_CURRENT_VIEW',
};

export const LOCATION_ERRORS = {
  LOCATION_ERROR: 'LOCATION_ERROR',
  NO_LOCATION: 'NO_LOCATION',
  OUTSIDE_SF: 'OUTSIDE_SF',
};

export const VIEW_FLOW = {
  ABOUT: 'ABOUT',
  LOADING_ANIMATION: 'LOADING_ANIMATION',
  LOCATION_WARNING: 'LOCATION_WARNING',
  MAIN_BUS: 'MAIN_BUS',
  MAIN_EARTHQUAKE: 'MAIN_EARTHQUAKE',
  MAIN_NOTHING: 'MAIN_NOTHING',
};

export const SF_BOUNDARIES = {
  NORTH: 37.833229,
  SOUTH: 37.708240,
  EAST: -122.328170,
  WEST: -122.517435,
};
