export const ACTIONS = {
  UPDATE_LOCATION_ATTRIBUTE: 'UPDATE_LOCATION_ATTRIBUTE',
  UPDATE_CURRENT_VIEW: 'UPDATE_CURRENT_VIEW',
};

export const LOCATION_ERRORS = {
  LOCATION_ERROR: 'LOCATION_ERROR',
  NO_LOCATION: 'NO_LOCATION',
  OUTSIDE_SF: 'OUTSIDE_SF',
};

export const VIEW_FLOW = {
  ABOUT: 'ABOUT',
  LOADING_ANIMATION: 'LOADING_ANIMATION',
  LOCATION_WARNING: 'LOCATION_WARNING',
  MAIN_CONTENT: 'MAIN_CONTENT',
};
